name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - "**/*.md"
      - LICENSE
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
      - "**/*.md"
      - LICENSE
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - name: Lint
        run: npx eslint src/ --no-error-on-unmatched-pattern || true
      - name: Build
        run: npx webpack --config webpack.config.js
      - name: Run tests
        run: npm test
